"""Configured knowledge sources for controlled ingestion.

URLs must be verified before enabling crawl_enabled in production.
"""

SOURCE_REGISTRY: list[dict] = [
    {
        "name": "TCS Services Overview",
        "publisher": "TCS",
        "provider": "TCS",
        "url": "https://www.tcsexpress.com/",
        "allowed_domains": ["www.tcsexpress.com", "tcsexpress.com"],
        "source_type": "provider_pricing",
        "authority_level": 1,
        "jurisdiction": "Pakistan",
        "topics": ["domestic", "international", "cod", "tracking"],
        "crawl_enabled": False,
        "search_enabled": True,
        "persist_to_rag": True,
    },
    {
        "name": "Leopards Courier Services",
        "publisher": "Leopards Courier",
        "provider": "Leopards",
        "url": "https://leopardscourier.com/",
        "allowed_domains": ["leopardscourier.com", "www.leopardscourier.com"],
        "source_type": "provider_policy",
        "authority_level": 1,
        "jurisdiction": "Pakistan",
        "topics": ["domestic", "ecommerce", "cod", "returns"],
        "crawl_enabled": False,
        "search_enabled": True,
        "persist_to_rag": True,
    },
    {
        "name": "DHL Pakistan Express",
        "publisher": "DHL",
        "provider": "DHL",
        "url": "https://www.dhl.com/pk-en",
        "allowed_domains": ["www.dhl.com", "dhl.com"],
        "source_type": "provider_policy",
        "authority_level": 1,
        "jurisdiction": "Pakistan",
        "topics": ["international", "customs", "documentation"],
        "crawl_enabled": False,
        "search_enabled": True,
        "persist_to_rag": True,
    },
    {
        "name": "M&P Courier (placeholder)",
        "publisher": "M&P",
        "provider": "M&P",
        "url": None,
        "allowed_domains": [],
        "source_type": "provider_policy",
        "authority_level": 1,
        "jurisdiction": "Pakistan",
        "topics": ["domestic", "cod"],
        "crawl_enabled": False,
        "search_enabled": False,
        "persist_to_rag": False,
        "note": "Enable after verifying official URL",
    },
    {
        "name": "BlueEX (placeholder)",
        "publisher": "BlueEX",
        "provider": "BlueEX",
        "url": None,
        "allowed_domains": [],
        "source_type": "provider_policy",
        "authority_level": 1,
        "jurisdiction": "Pakistan",
        "topics": ["ecommerce", "cod"],
        "crawl_enabled": False,
        "search_enabled": False,
        "persist_to_rag": False,
        "note": "Enable after verifying official URL",
    },
    {
        "name": "Trax (placeholder)",
        "publisher": "Trax",
        "provider": "Trax",
        "url": None,
        "allowed_domains": [],
        "source_type": "provider_policy",
        "authority_level": 1,
        "jurisdiction": "Pakistan",
        "topics": ["domestic"],
        "crawl_enabled": False,
        "search_enabled": False,
        "persist_to_rag": False,
        "note": "Enable after verifying official URL",
    },
]
